package br.com.github.gtvnv.audit.chain.domain;

public enum AuditEventType {

    // Autenticação
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_SUCCESS,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    CONSENT_GIVEN,
    CONSENT_WITHDRAWN,
    CONSENT_REQUIRED_BLOCKED,
    RETENTION_CHECKPOINT_CREATED,

    // Incident Response Orchestrator
    INCIDENT_OPENED,
    INCIDENT_ACKNOWLEDGED,
    INCIDENT_NOTIFIED,
    INCIDENT_RESOLVED,
    INCIDENT_SLA_BREACHED,

    // Network Sentinel
    NETWORK_UNTRUSTED_SOURCE_ALERTED,
    NETWORK_UNTRUSTED_SOURCE_BLOCKED,
    NETWORK_ZONE_CREATED,
    NETWORK_ZONE_DELETED,

    // Policy Audit
    POLICY_CREATED,
    POLICY_UPDATED,
    POLICY_DELETED,

    // Tokens
    TOKEN_ISSUED,
    REFRESH_TOKEN_ISSUED,
    TOKEN_REFRESHED,
    TOKEN_BLACKLIST_VIOLATION,
    REFRESH_TOKEN_USED_AS_ACCESS,

    // Controle de acesso (ABAC)
    ABAC_DECISION_PERMIT,
    ABAC_DECISION_DENY,

    // Ameaças (rate-limit e bloqueio)
    IP_RATE_LIMIT_EXCEEDED,
    IP_BLOCKED_EXPLICIT,

    // S.H.I.E.L.D.
    SHIELD_ALERT_TRIGGERED,
    SHIELD_REQUEST_BLOCKED,

    // KMS/Secrets — rotação de chave de assinatura
    SIGNING_KEY_ROTATED
}
